name: ci

on:
  pull_request:
  merge_group:

concurrency:
  group: >-
    ${{ github.workflow }}-${{
      github.event.pull_request.number
      || github.event.merge_group.head_ref
    }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    strategy:
      fail-fast: ${{ github.event_name == 'merge_group' }}
      matrix:
        build: [windows-x86_64]
        include:
        - build: windows-x86_64
          os: windows-2022
          cargo_flags: ""
    runs-on: ${{ matrix.os }}

    # TODO FIXME (aseipp): keep the timeout limit to ~15 minutes. this is long
    # enough to give us runway for the future, but also once we hit it, we're at
    # the "builds are taking too long" stage and we should start looking at ways
    # to optimize the CI.
    #
    # at the same time, this avoids some issues where some flaky, bugged tests
    # seem to be causing multi-hour runs on Windows (GPG signing issues), which
    # is a problem we should fix. in the mean time, this will make these flakes
    # less harmful, as it won't cause builds to spin for multiple hours, requiring
    # manual cancellation.
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        persist-credentials: false
    - name: Set up Windows Builders
      if: startswith(matrix.os, 'windows')
      uses: ./.github/actions/setup-windows
    - name: Install Rust
      uses: dtolnay/rust-toolchain@a54c7afa936fefeb4456b2dd8068152669aa8203
      with:
        toolchain: 1.84
        target: ${{ matrix.targets }}
    - uses: taiki-e/install-action@0f58b6a196e0d71c72fd459ab8fd8b228f85f669
      with:
        tool: nextest,taplo-cli
      env:
        HOME: '/d'
        PATH: ''
    - name: Install mold
      uses: rui314/setup-mold@f80524ca6eeaa76759b57fb78ddce5d87a20c720
      with:
        make-default: false
    - name: Build
      run: >-
        cargo build
        --config .cargo/config-ci.toml
        --workspace
        --all-targets
        --verbose
        ${{ matrix.cargo_flags }}
      env:
        LIBGIT2_NO_VENDOR: ${{ matrix.LIBGIT2_NO_VENDOR || '0' }}
    - name: Test
      run: >-
        cargo nextest run
        --config .cargo/config-ci.toml
        --workspace
        --all-targets
        --verbose
        --profile ci
        ${{ matrix.cargo_flags }}
      env:
        RUST_BACKTRACE: 1
        CARGO_TERM_COLOR: always
        LIBGIT2_NO_VENDOR: ${{ matrix.LIBGIT2_NO_VENDOR || '0' }}

  # Block the merge if required checks fail, but only in the merge
  # queue. See also `required-checks-hack.yml`.
  required-checks:
    name: required checks (merge queue)
    if: ${{ always() && github.event_name == 'merge_group' }}
    needs:
    - test
    runs-on: ubuntu-latest
    steps:
    - name: Block merge if required checks fail
      run: exit 1
